### ISSUE TITLE
auth 도메인, 회원가입

### ISSUE THREAD

**Issue by 0sunset0** [ShyPolarBear/Server#12]
## 📌  Feature Issue
auth 도메인 개발

## 📝  To-do

- [x] access token, refresh token 발급 로직
- [x] spring data jpa로 DB접근 레포지토리 개발
- [x] 회원가입 - 닉네임 중복 검증
- [ ] 회원가입 - 중복 회원 검증
- [ ] 회원가입 - 성공 시 토큰 발급
