### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by wonslee** [ShyPolarBear/Server#41]
## 📌  Feature Issue

CICD : github actions + docker

**CI** : PR 생성시 빌드 테스트. 
빌드 실패시 애플리케이션 자체가 작동 안 하므로 merge 불가능하게 설정해둘께요!

**CD** : PR merge (develop브랜치)시 AWS EC2 에 자동 배포

유의사항 및 상세 설명은 [Wiki](https://github.com/ShyPolarBear/Server/wiki/CI-CD)에 적어뒀습니다.

[정리해둔 노션 페이지](https://alike-pump-ae3.notion.site/Github-Actions-workflow-3cc2866e7cc043d4a9656ba818e46c21?pvs=4)

:warning:  막힘. RDS 연결 자체가 되지 않는 문제

시도해볼 것들
- vm options으로 `-Dcom.amazonaws.sdk.disableEc2Metadata=true` 추가 (Docker file)
![image](https://github.com/ShyPolarBear/Server/assets/72124326/66646a8a-62d8-4c65-90b5-2528071b4a8a)
- AWS 설정 다시... 꼼꼼히 보기

## 📝  To-do

- [x] ec2 pem키 받기
- [x] [인스턴스에 도커 설치](https://alike-pump-ae3.notion.site/86327f2bbe6a4eb3a90988b9735fedcd?pvs=4) 
- [x] docker hub 계정, 레포지토리 생성
- [x] Dockerfile 생성
- [x] 헬스체크 추가
- [x] 깃허브 admin 권한 받기
- [ ] github 환경변수 추가 (⚠️ .yml 파일은 [base64 인코딩](https://www.convertstring.com/ko/EncodeDecode/Base64Encode) 한 뒤에 넣어야 함)
- [ ] workflow 생성 -> deploy.yml 및 test_pr.yml 생성
- [x] .gitignore 수정 : *.yml -> application.yml
