### ISSUE TITLE
칼럼 제약 조건, @AuthenticationPrincipal, 테스트코드

### ISSUE THREAD

**Issue by 0sunset0** [ShyPolarBear/Server#54]
## 📝  To-do

- [x] 칼럼 제약 조건 (user, feed)
- [x] @AuthenticationPrincipal 적용 (웹 계층에 의존하게 하기)
- [ ] 테스트코드 작성 (이미지, 유저, 피드)
- [x] 유저 프로필 이미지 nullable
