### ISSUE TITLE
엔티티 객체 생성 코드 작성

### ISSUE THREAD

**Issue by 0sunset0** [ShyPolarBear/Server#9]
## 📌  Feature Issue
각 도메인의 객체를 생성할 수 있도록 한다.

## 📝  To-do

- [x] 연관관계 메서드 정의
- [x] 빌더 패턴 적용
- [x] 정적 팩토리 메서드
- [x] 객체 생성 테스트 코드
